# Generated by Django 4.2.5 on 2023-09-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='contenido')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='URL amigable')),
                ('visible', models.BooleanField(verbose_name='visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el:')),
                ('upgrade_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el :')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'paginas',
            },
        ),
    ]
