# Generated by Django 4.2.5 on 2023-09-26 19:51

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.CharField(max_length=255, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='titulo')),
                ('content', ckeditor.fields.RichTextField(verbose_name='contenido')),
                ('image', models.ImageField(default='null', upload_to='', verbose_name='imagen')),
                ('plublic', models.BooleanField(verbose_name='¿publicado?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('upgrate_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de actualizacion')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='blog.category', verbose_name='categotias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
